<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <PackageId>PerformanceComparison</PackageId>
        <Title>PerformanceComparison</Title>
        <Description>Benchmarks MoonSharp against NLua</Description>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\MoonSharp.Interpreter\MoonSharp.Interpreter.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NLua" Version="1.7.8" />
    </ItemGroup>

</Project>
