<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageId>MoonSharp.Hardwire</PackageId>
        <Title>MoonSharp.Hardwire</Title>
        <Description>Hardwired descriptor code generation for the MoonSharp interpreter</Description>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonSharp.Interpreter\MoonSharp.Interpreter.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.CodeDom" Version="4.5.0" />
    </ItemGroup>

</Project>
