<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <PackageId>MoonSharp</PackageId>
        <Title>MoonSharp</Title>
        <Description>REPL interpreter and command line tool for the MoonSharp language</Description>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonSharp.Hardwire\MoonSharp.Hardwire.csproj" />
        <ProjectReference Include="..\MoonSharp.Interpreter\MoonSharp.Interpreter.csproj" />
        <ProjectReference Include="..\MoonSharp.RemoteDebugger\MoonSharp.RemoteDebugger.csproj" />
    </ItemGroup>

</Project>
