<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageId>MoonSharp.Debugger.VsCode</PackageId>
        <Title>MoonSharp.VsCodeDebugger</Title>
        <Description>VS Code debug adapter for the MoonSharp interpreter</Description>
        <AssemblyOriginatorKeyFile>..\keypair.snk</AssemblyOriginatorKeyFile>
        <DefineConstants>$(DefineConstants);DOTNET_CORE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonSharp.Interpreter\MoonSharp.Interpreter.csproj" />
    </ItemGroup>

</Project>
