<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageId>Dustorm.MoonSharp.Plus</PackageId>
        <Title>Dustorm.MoonSharp.Plus</Title>
        <Description>An interpreter for the Lua language, extended with exact 'integer' (Int64) and 'decimal' (System.Decimal) numeric types with checked arithmetic. A fork of MoonSharp with non-pure-Lua extensions.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
        <DefineConstants>$(DefineConstants);DOTNET_CORE;HASDYNAMIC</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
