<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageId>MoonSharp.Debugger</PackageId>
        <Title>MoonSharp.RemoteDebugger</Title>
        <Description>Remote Debugger for the MoonSharp interpreter</Description>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>keypair.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonSharp.Interpreter\MoonSharp.Interpreter.csproj" />
    </ItemGroup>

</Project>
